version: '3'
services:

  telebot:
    image: onium16/pet_projects
    container_name: telebot_IR
    restart: unless-stopped
    tty: true
    ports:
      - '5000:5000'
    environment:
      - TOKEN=${TOKEN}
      - DB_URI=${DB_URI}
    depends_on:
      - ngrok
    command: python /app/api/index.py 
    env_file:
      - .env

  ngrok:
    image: ngrok/ngrok
    container_name: ngrok_host
    restart: unless-stopped
    tty: true
    ports:
      - '4040:4040'
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NAME_NGROK_CONTAINER=${NAME_NGROK_CONTAINER}
    command: http telebot:5000